import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 네비게이션 컴포넌트
function Navigation() {
  return (
    <header className="fixed top-0 left-0 w-full bg-white/95 backdrop-blur-sm shadow-sm z-50">
      <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
        
        {/* 로고 */}
        <Link
          href="/"
          className="text-black text-4xl font-bold font-['Comic_Neue'] leading-[54px]"
        >
          Medi
        </Link>

        {/* 메뉴 항목 */}
        <div className="hidden md:flex items-center space-x-6">
          <Link href="/informitem" className="text-sm text-gray-600 hover:text-blue-500">
            제품소개
          </Link>
          <Link href="/companyinform" className="text-sm text-gray-600 hover:text-blue-500">
            회사소개
          </Link>
          <Link href="/plan" className="text-sm text-gray-600 hover:text-blue-500">
            요금제
          </Link>
        </div>

        {/* 로그인/회원가입 버튼 */}
        <div className="flex items-center space-x-2">
          <Link href="/login">
            <Button variant="ghost">로그인</Button>
          </Link>
          <Link href="/hello">
            <Button>회원가입</Button>
          </Link>
        </div>
      </nav>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        <div className="pt-20">
          {children}
        </div>
      </body>
    </html>
  );
}
