import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import AuthInitializer from "@/components/AuthInitializer"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}

// 클라이언트 전용 래퍼
function ClientWrapper({ children }) {
  "use client";

  return (
    <StoreProvider>
      <AuthInitializer /> {/* import 한 AuthInitializer만 사용 */}
      {children}
    </StoreProvider>
  );
}
