import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import AuthInitializer from "@/components/AuthInitializer"; 

// font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// rootLayout(server component)
export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}

// 클라이언트 전용 래퍼
// client wrapper(client component)
// <StoreProvider> : Redux store provider
// <AuthInitializer> : Checks session(backend) and restores auth status on app load
function ClientWrapper({ children }) {
  "use client";

  return (
    <StoreProvider>
      <AuthInitializer /> {/* import 한 AuthInitializer만 사용 */}
      {children}
    </StoreProvider>
  );
}
